class CMD:
    CANCEL = "cancel"
    MENU = "menu"
    START = "start"
    CREATE_RECORD = "add_record"
    CREATE_STRATEGY = "set_strateg"
    CREATE_SCENARIO = "create_scenario"
    SCENARIOS_LIST = "get_my_scenarios"
    DELETE_SCENARIO = "delete_scenario"
    FILL_SCENARIO = "fill_scenario"
    RENAME_SCENARIO = "rename_scenario"
    CONFIRM = "confirm"
    DENY = "deny"
    BACK_TO_SCENARIOS = "back_to_scenarios"
    SHOW_PARAMETERS = "show_parameters"
    BACK_TO_OPTIONS = "back_to_options"
