"""alter parameters default_value to string and drop user_scenarios scenario_id unique constraint

Revision ID: 04b4fd1383c5
Revises: 946c7d1eb4c4
Create Date: 2026-01-08 16:40:49.880739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b4fd1383c5'
down_revision: Union[str, Sequence[str], None] = '946c7d1eb4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parameters', 'default_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_scenarios_scenario_id_key'), 'user_scenarios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_scenarios_scenario_id_key'), 'user_scenarios', ['scenario_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('parameters', 'default_value',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
